name: Deploy JAR to GitHub Packages

on:
  push:
    branches:
      - master  # or the branch you want to trigger deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Needed to publish packages

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Build and Deploy with Maven
        run: mvn clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_TOKEN }}
